version: "3.9"

services:

  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    command: npm run start
    restart: unless-stopped
    depends_on:
      - backend